[package]
name = "topola-cli"
description = "Work-in-progress free and open-source topological (rubberband) router and autorouter for printed circuit boards (PCBs)"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "topola"
path = "src/main.rs"

[features]
default = ["disable_contracts"]
disable_contracts = ["topola/disable_contracts"]

[dependencies]
serde.workspace = true
serde_json.workspace = true

[dependencies.topola]
path = "../.."
default-features = false

[dependencies.clap]
version = "4.5"
features = ["derive"]

[build-dependencies]
clap_mangen = "0.2"

[build-dependencies.clap]
version = "4.5"
features = ["derive"]
