# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    #-   id: clippy
        #args: []
    -   id: cargo-check
-   repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
    -   id: reuse-lint-file
#-   repo: https://github.com/crate-ci/committed
    #rev: v1.1.7
    #hooks:
    #-   id: committed
        #stages: [commit-msg]
