[package]
name = "topola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.geo]
version = "0.25.1"

[dependencies.rstar]
version = "0.11.0"

[dependencies.petgraph]
version = "0.6.3"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]

[dependencies.enum-as-inner]
version = "0.6.0"
