[package]
name = "topola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sdl2_demo"]
sdl2_demo = ["dep:sdl2"]

[dependencies]
gl = "0.14.0"
pathfinder_canvas = { git = "https://github.com/servo/pathfinder" }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder" }
pathfinder_gl = { git = "https://github.com/servo/pathfinder" }
pathfinder_renderer = { git = "https://github.com/servo/pathfinder" }
pathfinder_resources = { git = "https://github.com/servo/pathfinder" }
thiserror = "1.0.56"
anyhow = "1.0.79"

[dependencies.geo]
version = "0.25.1"

[dependencies.rstar]
version = "0.11.0"

[dependencies.petgraph]
version = "0.6.3"

[dependencies.spade]
version = "2.2.0"

[dependencies.enum_dispatch]
version = "0.3.12"

[dependencies.itertools]
version = "0.8.2"

[dependencies.contracts]
version = "0.6.3"

[dependencies.sdl2]
version = "0.35.2"
optional = true
default-features = false
features = ["bundled"]

[patch.crates-io]
contracts = { path = "vendored/contracts" }
