# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

[workspace]
members = ["specctra", "specctra_derive", "topola", "topola-egui"]
default-members = ["specctra", "specctra_derive", "topola"]
resolver = "2"

[workspace.dependencies]
derive-getters = "0.5"
derive_more = { version = "2.1", features = ["full"] }
num-traits = "0.2"
serde = { version = "1", features = ["derive", "rc"] }
thiserror = "2.0"
undoredo = { version = "0.14", features = ["derive", "bidimap", "stable-vec", "rstar"] }

[profile.release]
opt-level = 2 # Fast and small WASM.

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
