[package]
name = "topola"
version = "0.1.0"
edition = "2021"
default-run = "topola-egui"

[lib]
name = "topola"

[[bin]]
name = "topola-egui"
required-features = ["egui"]

[[bin]]
name = "topola-sdl2-demo"
required-features = ["sdl2"]

[features]
egui = ["dep:eframe", "dep:egui"]
sdl2 = ["dep:sdl2"]

[dependencies]
rfd = "0.14.0"
gl = "0.14.0"
pathfinder_canvas = { git = "https://github.com/servo/pathfinder" }
pathfinder_geometry = { git = "https://github.com/servo/pathfinder" }
pathfinder_gl = { git = "https://github.com/servo/pathfinder" }
pathfinder_renderer = { git = "https://github.com/servo/pathfinder" }
pathfinder_resources = { git = "https://github.com/servo/pathfinder" }
thiserror = "1.0.56"
anyhow = "1.0.79"
geo = "0.25.1"
rstar = "0.11.0"
petgraph = "0.6.3"
spade = "2.2.0"
enum_dispatch = "0.3.12"
itertools = "0.8.2"
futures = "0.3.30"
contracts = "0.6.3"
log = "0.4"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.eframe]
optional = true
version = "0.26.0"
default-features = false
features = ["accesskit", "default_fonts", "glow", "persistence"]

[dependencies.egui]
optional = true
version = "0.26.0"

[dependencies.sdl2]
optional = true
version = "0.35.2"
default-features = false
features = ["bundled"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
contracts = { path = "vendored/contracts" }
