# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "assets/**"
SPDX-FileCopyrightText = "2024 Topola contributors"
SPDX-License-Identifier = "CC-BY-4.0 OR MIT"

[[annotations]]
path = "locales/**"
SPDX-FileCopyrightText = "2024 Topola contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "crates/planar-incr-embed/tests/**",
    "crates/planar-incr-embed/src/planarr/snapshots/**",
    "tests/unilayer/**",
    "tests/multilayer/**"
]
SPDX-FileCopyrightText = "2024 Topola contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "2024 Topola contributors"
SPDX-License-Identifier = "MIT"
