# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

[package]
name = "topola-egui"
description = "Work-in-progress free and open-source topological (rubberband) router and autorouter for printed circuit boards (PCBs)"
version = "0.1.0"
edition = "2021"

[features]
default = ["disable_contracts", "xdg-portal"]
disable_contracts = ["topola/disable_contracts"]
gtk3 = ["rfd/gtk3"]
xdg-portal = ["rfd/async-std", "rfd/xdg-portal"]

[dependencies]
derive-getters.workspace = true
egui = "0.31"
fluent-templates = "0.13"
geo.workspace = true
icu_experimental = "0.2"
icu_locale_core = "2.0.0-beta1"
log.workspace = true
petgraph.workspace = true
rstar.workspace = true
serde.workspace = true
serde_json.workspace = true
spade.workspace = true
sys-locale = "0.3"

[dependencies.topola]
path = "../.."
default-features = false

[dependencies.unic-langid]
version = "0.9"
features = ["macros", "serde"]

[dependencies.eframe]
version = "0.31"
default-features = false
features = ["accesskit", "default_fonts", "glow", "persistence", "wayland", "x11"]

[dependencies.rfd]
version = "0.15"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-lite = "2.6"
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
