# SPDX-FileCopyrightText: 2026 Topola contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "topola"
description = "Work-in-progress free and open-source topological (rubberband) router and autorouter for printed circuit boards (PCBs)"
version = "0.1.0"
edition = "2024"

[dependencies]
bimap = "0.6"
dearcut = { version = "0.2", features = ["undoredo"] }
derive-getters.workspace = true
derive_more.workspace = true
serde.workspace = true
specctra = { path = "../specctra" }
stable-vec = "0.4"
undoredo.workspace = true

[dev-dependencies]
walkdir = "2.5"
