# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

[package]
name = "specctra-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap.workspace = true
geo-types.workspace = true
serde.workspace = true
specctra_derive.path = "../specctra_derive"
thiserror.workspace = true
utf8-chars = "3.0"
