matrix:
  include:
    - CHANNEL: stable
      FEATURES: sdl2,disable_contracts
    - CHANNEL: nightly
      FEATURES: sdl2

steps:
  build_sdl2:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - apt-get update
      - apt-get -y install cmake
      - rustup default "$CHANNEL"
      - cargo build --features "$FEATURES" --bin "topola-sdl2-demo"
