# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

matrix:
  include:
    - CHANNEL: stable
      FEATURES: disable_contracts
    - CHANNEL: nightly
      FEATURES:

steps:
  build_egui:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
    commands:
      - rustup default "$CHANNEL"
      - cargo build -p topola-egui --no-default-features --features "$FEATURES"
    when:
      event: [pull_request, push, tag]
