matrix:
  include:
    - CHANNEL: stable
      FEATURES: egui,disable_contracts
    - CHANNEL: nightly
      FEATURES: egui

steps:
  build_wasm:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARG_TERM_COLOR: always
    commands:
      - apt-get -y install curl
      - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
      - cargo binstall --no-confirm trunk
      - rustup default "$CHANNEL"
      - rustup target add wasm32-unknown-unknown
      - trunk build
    when:
      event: [pull_request, push, tag]
