matrix:
  include:
    - CHANNEL: stable
      FEATURES: egui,disable_contracts
    - CHANNEL: nightly
      FEATURES: egui

steps:
  build_egui:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default "$CHANNEL"
      - cargo build --features "$FEATURES" --bin "topola-egui"
