# SPDX-FileCopyrightText: 2024 Topola contributors
#
# SPDX-License-Identifier: MIT

steps:
  check_formatting:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
    commands:
      - cargo install committed
      - committed develop..HEAD
      - committed HEAD
      - rustup component add rustfmt
      - cargo fmt --all -- --check
    when:
      event: [pull_request, push, tag]
