steps:
  check_formatting:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
    commands:
      - rustup component add rustfmt
      - cargo fmt --all -- --check
    when:
      event: [pull_request, push, tag]
