steps:
  lint:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
    commands:
      - rustup default stable
      - cargo fmt --check
      - cargo clippy
    failure: ignore # TODO: remove this when all clippy problems were addressed
    when:
      event: [pull_request, push, tag]
