steps:
  lint:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TERM_COLOR: always
    commands:
      - rustup default stable
      - rustup component add rustfmt clippy
      - cargo fmt --check
      - cargo clippy
    when:
      event: [pull_request, push, tag]
